/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistempakar;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author harun
 */
public class FormUser extends javax.swing.JFrame {

    /**
     * Creates new form FormUser
     */
    Connection koneksi;

    public FormUser(java.awt.Frame parent, boolean modal) {
        initComponents();
        koneksi = Koneksi.getKoneksi("localhost", "3306", "root", "", "db_pakar");
        Gejala1();
        Gejala2();
        Gejala3();
        
    }

    public void Gejala1() {
        try {
            Statement stmt = koneksi.createStatement();
            String query = "SELECT * FROM penyakit GROUP BY gejala1";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                cmbG1.addItem(rs.getString("gejala1"));
//                cmbG1.addItem(rs.getString("gejala2"));
//                cmbG1.addItem(rs.getString("gejala3"));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void Gejala2() {
        try {
            Statement stmt = koneksi.createStatement();
            String query = "SELECT * FROM penyakit GROUP BY gejala2";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                //cmbG2.addItem(rs.getString("gejala1"));
                cmbG2.addItem(rs.getString("gejala2"));
                //cmbG2.addItem(rs.getString("gejala3"));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void Gejala3() {
        try {
            Statement stmt = koneksi.createStatement();
            String query = "SELECT * FROM penyakit GROUP BY gejala3";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                //cmbG3.addItem(rs.getString("gejala1"));
                //cmbG3.addItem(rs.getString("gejala2"));
                cmbG3.addItem(rs.getString("gejala3"));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void Diagnosa() {
        String gjl1 = cmbG1.getSelectedItem().toString();
        String gjl2 = cmbG2.getSelectedItem().toString();
        String gjl3 = cmbG3.getSelectedItem().toString();
        try {
            Statement stmt = koneksi.createStatement();
            String query = "SELECT * FROM penyakit WHERE gejala1 = '"+gjl1+"' AND gejala2 = '"+gjl2+"' AND gejala3 = '"+gjl3+"'";
//                    "SELECT * FROM penyakit WHERE gejala1 = '"+gjl1+"' OR gejala2 = '"+gjl1+"' OR gejala3 = '"+gjl1+"' AND "
//                    + "gejala1 = '"+gjl2+"' OR gejala2 = '"+gjl2+"' OR gejala3 = '"+gjl2+"' AND "
//                    + "gejala1 = '"+gjl3+"' AND gejala2 = '"+gjl3+"' AND gejala3 = '"+gjl3+"'";
            System.out.println(query);
            ResultSet berhasil = stmt.executeQuery(query);
            if (berhasil.next()) {
                String sick = berhasil.getString("diagnosa");
                JOptionPane.showMessageDialog(null, "Penyakit yang Diderita Adalah : " + sick);
                lblsick.setText(""+berhasil.getString(5));
                txtcegah.setText(""+berhasil.getString(6));
                
            } else {
                JOptionPane.showMessageDialog(null, "Mohon Maaf, Penyakit Tidak Ada. Silahkan Menghubungi Dokter Untuk Konsultasi");
                lblsick.setText("Mohon Maaf, Penyakit Tidak Ada.");
                txtcegah.setText("Harap Segera Menghubungi Dokter Untuk Melakukan Konsultasi ");
            }
        } catch (Exception e) {
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbG1 = new javax.swing.JComboBox<>();
        cmbG2 = new javax.swing.JComboBox<>();
        cmbG3 = new javax.swing.JComboBox<>();
        btnCari = new javax.swing.JButton();
        btnOut = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblsick = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtcegah = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnAbout = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cek Panyakit");

        jLabel2.setFont(new java.awt.Font("Bebas", 0, 24)); // NOI18N
        jLabel2.setText("Panyakit Detector");

        jLabel3.setFont(new java.awt.Font("Bebas", 0, 14)); // NOI18N
        jLabel3.setText("Gejala Pertama");

        jLabel1.setFont(new java.awt.Font("Bebas", 0, 14)); // NOI18N
        jLabel1.setText("Gejala Kedua");

        jLabel4.setFont(new java.awt.Font("Bebas", 0, 14)); // NOI18N
        jLabel4.setText("Gejala Ketiga");

        cmbG1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbG1FocusGained(evt);
            }
        });
        cmbG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbG1ActionPerformed(evt);
            }
        });

        cmbG2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbG2FocusGained(evt);
            }
        });

        cmbG3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbG3FocusGained(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistempakar/search.png"))); // NOI18N
        btnCari.setText("Diagnosa Panyakit");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnOut.setText("Logout");
        btnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Hasil Diagnosa");

        jLabel6.setText("Penyakit Yang Diderita : ");

        jLabel7.setText("Penyebab dan Pencegahan : ");

        txtcegah.setColumns(20);
        txtcegah.setRows(5);
        jScrollPane1.setViewportView(txtcegah);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblsick))
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(173, 173, 173))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblsick))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        mnFile.setText("File");
        mnFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnFileMouseClicked(evt);
            }
        });

        mnAbout.setText("About");
        mnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAboutActionPerformed(evt);
            }
        });
        mnFile.add(mnAbout);

        jMenuBar1.add(mnFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbG2, 0, 270, Short.MAX_VALUE)
                            .addComponent(cmbG3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbG1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbG1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbG2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbG3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOut))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbG1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbG1ActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        Diagnosa();
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "Anda Yakin Ingin Keluar?", "Logout", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        if(input == JOptionPane.YES_OPTION){
            LoginForm fl = new LoginForm();
            fl.show();
            this.dispose();
        }
        
    }//GEN-LAST:event_btnOutActionPerformed

    private void mnFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnFileMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnFileMouseClicked

    private void mnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAboutActionPerformed
        // TODO add your handling code here:
        new About(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_mnAboutActionPerformed

    private void cmbG1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbG1FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbG1FocusGained

    private void cmbG2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbG2FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbG2FocusGained

    private void cmbG3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbG3FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbG3FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnOut;
    private javax.swing.JComboBox<String> cmbG1;
    private javax.swing.JComboBox<String> cmbG2;
    private javax.swing.JComboBox<String> cmbG3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblsick;
    private javax.swing.JMenuItem mnAbout;
    private javax.swing.JMenu mnFile;
    private javax.swing.JTextArea txtcegah;
    // End of variables declaration//GEN-END:variables
}
