/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistempakar;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author harun
 */
public class ManageSick extends javax.swing.JDialog {

    /**
     * Creates new form ManageSick
     */
    Connection koneksi;
    String action, id_sick;

    public ManageSick(java.awt.Frame parent, boolean modal, String act, String id) {
        super(parent, modal);
        initComponents();
        koneksi = Koneksi.getKoneksi("localhost", "3306", "root", "", "db_pakar");
        action = act;
        id_sick = id;
        if (act.equals("add")) {
            lbl_title.setText("Tambah Penyakit");
            ShowSick(act, null);
            tb_id.setEnabled(true);
        } else if (act.equals("edit")) {
            lbl_title.setText("Edit Penyakit");
            ShowSick(act, id);
            tb_id.setEnabled(false);
        }
    }

    void ShowSick(String act, String id) {
        if (action.equals("edit")) {
            try {
                Statement stmt = koneksi.createStatement();
                String query = "SELECT * FROM penyakit WHERE id = '"+id+"'";
                ResultSet rs = stmt.executeQuery(query);
                rs.first();
                tb_id.setText(rs.getString("id"));
                tb_gj1.setText(rs.getString("gejala1"));
                tb_gj2.setText(rs.getString("gejala2"));
                tb_gj3.setText(rs.getString("gejala3"));
                tb_sick.setText(rs.getString("diagnosa"));
                txtcgh.setText(rs.getString("cegah"));
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Kesalahan DB or Query");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tb_id = new javax.swing.JTextField();
        tb_gj1 = new javax.swing.JTextField();
        tb_gj2 = new javax.swing.JTextField();
        tb_gj3 = new javax.swing.JTextField();
        tb_sick = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtcgh = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Panyakit");

        lbl_title.setFont(new java.awt.Font("Bebas", 0, 18)); // NOI18N
        lbl_title.setText("Manage Data Penyakit");

        jLabel2.setFont(new java.awt.Font("Bebas", 0, 11)); // NOI18N
        jLabel2.setText("ID Penyakit");

        jLabel3.setFont(new java.awt.Font("Bebas", 0, 11)); // NOI18N
        jLabel3.setText("Gejala 1");

        jLabel4.setFont(new java.awt.Font("Bebas", 0, 11)); // NOI18N
        jLabel4.setText("Gejala 2");

        jLabel5.setFont(new java.awt.Font("Bebas", 0, 11)); // NOI18N
        jLabel5.setText("Gejala 3");

        jLabel6.setFont(new java.awt.Font("Bebas", 0, 11)); // NOI18N
        jLabel6.setText("Penyakit");

        tb_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_idActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Impact", 0, 11)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistempakar/save.png"))); // NOI18N
        btnSave.setText("Simpan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel1.setText("Penyebab dan Penanganan Pertama");

        txtcgh.setColumns(20);
        txtcgh.setRows(5);
        jScrollPane1.setViewportView(txtcgh);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tb_id)
                            .addComponent(tb_sick, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tb_gj3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tb_gj2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tb_gj1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_title)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbl_title)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tb_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tb_gj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tb_gj2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tb_sick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tb_gj3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        FormAdmin fa = new FormAdmin();

        String id = tb_id.getText();
        String gj1 = tb_gj1.getText();
        String gj2 = tb_gj2.getText();
        String gj3 = tb_gj3.getText();
        String sick = tb_sick.getText();
        String cgh = txtcgh.getText();

        if (action.equals("add")) {
            lbl_title.setText("Tambah Penyakit");
            try {
                Statement stmt = koneksi.createStatement();
                String query = "INSERT INTO penyakit(id,gejala1,gejala2,gejala3,diagnosa,cegah)"
                        + "VALUES ('" + id + "','" + gj1 + "','" + gj2 + "','" + gj3 + "','" + sick + "','"+ cgh +"')";
                System.out.println(query);
                int berhasil = stmt.executeUpdate(query);
                if (berhasil == 1) {
                    JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
                } else {
                    JOptionPane.showMessageDialog(null, "Data Gagal Ditambahkan");
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Kesalahan DB or Query");
            }
            fa.ShowData();
            setVisible(false);
        } else {
            lbl_title.setText("Edit Penyakit");
            try {
                Statement stmt = koneksi.createStatement();
                String query = "UPDATE penyakit SET id='" + id + "', "
                        + "gejala1='" + gj1 + "', gejala2='" + gj2 + "', "
                        + "gejala3='" + gj3 + "', diagnosa='" + sick + "', cegah= '"+ cgh +"' WHERE id='" + id + "'";
                System.out.println(query);
                int berhasil = stmt.executeUpdate(query);
                if (berhasil == 1) {
                    JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
                } else {
                    JOptionPane.showMessageDialog(null, "Data Gagal Diubah");
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Terjadi Kesalahan pada Query");
            }
            fa.ShowData();
            setVisible(false);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tb_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_idActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ManageSick.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ManageSick.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ManageSick.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ManageSick.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ManageSick dialog = new ManageSick(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField tb_gj1;
    private javax.swing.JTextField tb_gj2;
    private javax.swing.JTextField tb_gj3;
    private javax.swing.JTextField tb_id;
    private javax.swing.JTextField tb_sick;
    private javax.swing.JTextArea txtcgh;
    // End of variables declaration//GEN-END:variables
}
